### ISSUE TITLE
aws token required but not using it

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/SynapseBucketMover#1]
I get:

```
SynapseBucketMover.py: error: the following arguments are required: -awstoken/--awsSessionToken
```

But the directions specify I should only need this if I am using MFA.

**Comment by brucehoff** [comment]
https://github.com/Sage-Bionetworks/SynapseBucketMover/commit/b9b100fcc712140b41d9315086ea3a3a25e04547
